export const explorerPaths = {
  root: "root",
  keyspaces: "keyspaces",
  ks: (ks: string) => `ks/${ks}`,
  ksTables: (ks: string) => `ks/${ks}/tables`,
  ksTbl: (ks: string, t: string) => `ks/${ks}/tbl/${t}`,
  ksCols: (ks: string, t: string) => `ks/${ks}/tbl/${t}/columns`,
  ksTblIdx: (ks: string, t: string) => `ks/${ks}/tbl/${t}/indexes`,
  ksTblViews: (ks: string, t: string) => `ks/${ks}/tbl/${t}/views`,
  ksIdx: (ks: string) => `ks/${ks}/indexes`,
  ksViews: (ks: string) => `ks/${ks}/views`,
  ksTypes: (ks: string) => `ks/${ks}/types`,
  ksFunctions: (ks: string) => `ks/${ks}/functions`,
  ksAggregates: (ks: string) => `ks/${ks}/aggregates`,
  functions: "functions",
  aggregates: "aggregates",
  roles: "roles",
  permissions: "permissions",
  sysKs: "sys/keyspaces",
} as const;
